**출처**
- [Do it! 자바 프로그래밍 입문](http://www.kyobobook.co.kr/product/detailViewKor.laf?mallGb=KOR&ejkGb=KOR&barcode=9791163030195)
- [https://www.nowwatersblog.com/cs/Exception](https://www.nowwatersblog.com/cs/Exception)
- [https://wonyong-jang.github.io/java/2021/01/14/Java-Exception-Handling.html](https://wonyong-jang.github.io/java/2021/01/14/Java-Exception-Handling.html)
- [https://read-write-developer.tistory.com/121?category=819503](https://read-write-developer.tistory.com/121?category=819503)
- [https://youn12.tistory.com/32](https://youn12.tistory.com/32)
- [https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC](https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)
- [https://dololak.tistory.com/61](https://dololak.tistory.com/61)
---

**학습할것(필수)**

- Exception과 Error의 차이는?
- 자바가 제공하는 예외 계층 구조
- RuntimeException과 RE가 아닌 것의 차이는?
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 커스텀한 예외 만드는 방법

---
<br>

### 1. Exception과 Error의 차이는?
**Error**

하드웨어의 오작동 또는 고장으로 인해 응용프로그램에 이상이 생겼거나 JVM 실행에 문제가 생겼을 경우 발생한다.

- 프로그램에서 제어 할 수 없다.
- Error 클래스의 하위 클래스는 시스템에서 발생하는 오류를 다루며, 프로그램에서 제어하지 않는다.
- Error 발생 시 프로그램은 비정상적으로 종료된다.
- EX) 사용 가능한 동적 메모리가 없는 경우, 스택 메모리의 오버플로 발생

**Exception**

사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류
- 프로그램에서 제어 할 수 있다.
- 보통 프로그램 실행 중 발생
- EX) 프로그램에서 파일을 읽어 사용하려는데 파일이 없는 경우, 네트워크로 데이터를 전송하려는데 연결이 안 된 경우, 배열 값을 출력하려는데 배열 요소가 없는 경우

<br>

### 2. 자바가 제공하는 예외 계층 구조
Exception과 Error는 Throwable을 상속한다.

![image](https://user-images.githubusercontent.com/26623547/104831615-f6f93800-58cd-11eb-9682-e192bab57851.png)

**Error**
- Error 클래스와 하위 클래스들이 속한다. 예상 할 수 없고 복구 할수 없다.

Exception은 `Checked Exception`과 `UnChecked Exception`으로 나뉜다.

**1. Checked Exception**
###### Exception의 하위 클래스 중 RuntimeException을 제외한 모든 Exception
- `컴파일 시점에 발생 하는 예외이다.`
  - try-catch 또는 throws를 통해 처리를 해줘야 컴파일이 된다.

**2. UnChecked Exception**
###### RuntimeException을 상속받은 Exception
- `컴파일 시점에 확인되지 않는 예외이다.`
  - 발생을 예측할 수 없고, 복구할 수 없는 예외

<br>

### 3. RuntimeException과 RE가 아닌 것의 차이는?

**RuntimeException**은 `Checked Exception`과 `UnChecked Exception`을 구분하는 기준이다.

Exception의 자식 클래스 중 RuntimeException을 제외한 모든 Exception은 Checked Exception이며,
RuntimeException클래스와 자식들은 UnChecked Exception이다.


<br>

### 4. 자바에서 예외 처리 방법

**try영역** 
- 실행 코드 영역

**catch영역**
- try에서 Exception 발생 시 처리 코드 영역
- 예외 발생 시 JVM이 예외 객체를 만들어 catch영역으로 던진다. catch에서는 해당 예외객체와 변수를 선언해주어야 한다.

**throw**
- 강제로 예외를 발생 시키는 키워드

**throws**
- 예외가 발생한 함수를 호출한 함수에게 던진다.
- try-catch구문이나 throws를 사용하지 않으면 JVM이 해당 예외를 처리한다.

**finally**
- try-catch문에서 예외가 발생하건 안하건 catch가 실행되건 안하건 무조건 실행된다.
- 보통 리소스 정리 및 파일 close에 사용

**꼭 필요한 곳에서만 예외처리 사용!**
> 일반적으로 try구문 안에서의 코드가 try밖에 위치한 코드보다 느리다고 한다.

<br>
---

**1. 기본 try-catch**
```java
class test {
  void Exception() {
    try {
        //실행 코드
    } catch (Exception1 ex1) {
        //Exception1 처리 코드
    } catch (Exception2 ex2) {
        //Exception2 처리 코드
    }
  }
}
```

<br>

**2. finally**

try-catch 과정에서 어떤 예외 상황이 발생해도 반드시 finally 영역이 실행 된다.
```java
class test {
  void Exception() {
    try {
        //실행 코드
    } catch (Exception1 ex1) {
        //Exception1 처리 코드
    } finally {
        //반드시 실행되는 코드
    }
  }
}
```

<br>

**예외문에서 return 사용 시 주의점**
- finally 블록 내에 문장은 try, catch 블록에 return문이 있더라도 실행 된다.
- try 블록에서의 return 
  - try 리턴값 리턴
- catch 블록에서의 return 
  - catch 리턴값 리턴
- finally 블록에서의 return
  - try-catch에서 Exception이 발생을 해도 return의 제어권은 finally가 가져오게 된다. 오류인 상황이 발생을 해야 하지만 정상적으로 값이 전달 된 것으로 처리.
  - 위와 같은 경우 때문에 finally에서 return을 사용하면 안됨(Anti Pattern)
  

<br>

**3. Multicatch block**
- 자바 7부터 catch block을 합칠 수 있다.
- 다수의 Exception을 하나의 로직으로 처리할 수 있다.

**주의점**
- multicatch block으로 묶인 예외는 부모-자식 관계에 있으면 안된다.
  - 자식 클래스로 잡아낼 수 있는 예외는 부모클래스로도 잡아낼 수 있기 떄문에 사실상 중복 된 것 
- multicatch block에 사용된 예외들의 공통된 조상의 멤버만 사용 할 수 있다.
  - 해당 변수가 어느 예외 인지 판단 할수 없기때문에, instanceo로 체크, 형변환 후 사용 해야 한다. 
```java
class test {
  void Exception(){
        try {
            // 실행 코드
        }catch (Exception1 | Exception2 | Exception3 exception){
            // Exception1, Exception2, Exception3 예외 처리 코드
        }
    }
    
}
```

<br>

**4. try-with-resource**
- 자바 7부터 사용 가능하다.
- `try(...)안에서 선언된 객체들에 대해 try가 종료 될때 자동으로 자원을 해체해주는 기능이다.`
- finally에서 close()를 명시적으로 호출해줄 필요가 없다.
- try-with-resources에서 자동으로 close가 호출되는 것은 `AutoCloseable`을 구현한 객체에만 해당 된다.
  - 커스텀한 클래스의 자원도 해체되길 원하면 AutoCloseable을 구현하면 된다.

```java
class Test {
  void resourceException(){
    try(BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));) {
        //실행 코드
    } catch (Exception e) {
      e.printStackTrace();
    }
  } 
}
```
- try문을 벗어나면 BufferedReader을 close()한다.
- 코드를 짧고 간결하게 만들어 읽기 쉽고, 유지보수가 쉬워진다.



<br>

### 5. 커스텀한 예외 만드는 방법

- Checked Exception을 구현하기 위해서는 Exception 클래스를 상속받는다.
- Unchecked Exception을 구현하기 위해서는 RuntimeException 클래스를 상속받는다.


