[자바에서 예외 처리 방법 (try, catch, throw, throws, finally)](#자바에서-예외-처리-방법-try-catch-throw-throws-finally) <br>
[Exception과 Error의 차이는?](#exception과-error의-차이는) <br>
[자바가 제공하는 예외 계층 구조](#자바가-제공하는-예외-계층-구조) <br>
[RuntimeException과 RE가 아닌 것의 차이는?](#runtimeexception과-re가-아닌-것의-차이는) <br>
[커스텀한 예외 만드는 방법](#커스텀한-예외-만드는-방법) <br>

<br><br><br>

## 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)

1. **try-catch**

```java
try {
 // 예외 발생 가능 코드
} catch (Exception1 e1) {
 // Exception1이 발생했을 때, 이를 처리하기 위한 코드
} catch (Exception2 e2) {
 // Exception2가 발생했을 때, 이를 처리하기 위한 코드
} catch (ExceptionN eN) {
 // ExceptionN이 발생했을 때, 이를 처리하기 위한 코드
}
```

- try 블럭에 여러 개의 catch 블럭 가능
    - 이 중 **발생한 예외의 종류와 일치하는 단 한 개의 catch 블록만 수행**
    - catch 블럭 안에 다시 try-catch 구문 사용 가능 but **상위 catch 블록 안에 참조 변수의 이름 중복 불가**
    - 참조변수를 통해 에러 메시지 출력 가능
        - printStackTrace()
            - 예외 발생 당시의 호출스택에 있었던 메서드 정보와 예외 메시지 출력
            - 많은 시스템 자원을 소모하므로 정말 필요한 경우가 아니면 사용 X
        - getMessage()
            - 발생한 예외클래스의 인스턴스에 저장된 메시지 출력
- **Multicatch block**
    
    ```java
    try {
     // 예외 발생 가능 코드
    } catch (Exception1 | Exception2 e) {
     // Exception1, Exception2 에러 발생 가능
    }
    ```
    
    - JDK 1.7부터 여러 catch block을 하나로 작성 가능
    - 나열된 예외 클래스들이 부모-자식 관계에 있다면 오류가 발생
    - 자식 클래스로 잡아낼 수 있는 예외는 부모 클래스로도 잡기 가능 → 사실상 코드가 중복된 것이기 때문에 컴파일러는 중복된 코드를 제거하라는 의미에서 에러를 발생시킴
    - 하나의 블록으로 여러 예외를 처리 → 멀티 캐치 블록 내에서는 발생한 예외가 정확이 어디에 속한 것인지 알 수 없음 ⇒ 그래서 **참조 변수 e에는 ‘|’로 연결된 예외들의 공통 조상 클래스에 대한 정보가 담김**

<br>

2. **throw**

throw 키워드를 이용해서 고의로 예외를 발생시킴

```java
if (에러가 발생하면) {
 throw new Exception("에러를 던져준다.");
}
```

<br>

3. **throws**

```java
void method() throws Exception1, Exception2, … ExceptionN {
    // 메서드 내용
}
```

- 메서드에 예외를 선언 가능
- 여러 개의 메서드를 쉼표로 구분해서 선언
- 해당 메서드에서 예외를 처리하지 않고, 해당 메서드를 사용하는 쪽이 예외를 처리하도록 책임을 전가하는 역할

<br>

4. **finally**

```java
try {
  // 예외가 발생할 가능성이 있는 문장
} catch {
  // 예외 처리를 위한 문장
} finally {
  // 예외 발생 여부와 상관없이 항상 실행되어야 할 문장
}
```

- try-catch와 함께 예외의 발생 여부와 상관없이 항상 실행되어야 할 코드를 포함시킬 목적으로 사용
- try-catch문의 끝에 선택적으로 덧붙여 사용할 수 있으며, try-catch-finally의 순서로 구성
- 예외가 발생한 경우: try -> catch -> finally 순으로 실행
- 예외가 발생하지 않은 경우: try - finally 순으로 실행
- **finally 블록 내의 문장은 try, catch 블록에 return문이 있더라도 실행**

<br>

5. **try - with - resources**
- exception시 resources를 자동으로 close()
- 자바 7부터 추가
- 사용 로직을 작성할 때 **객체는 AutoCloseable 인터페이스를 구현한 객체**여야 함
    
    ```java
    public interface AutoCloseable {
        void close() throws Exception;
    }
    ```

<br>

6. **try ~ catch ~ finally**

![image](https://user-images.githubusercontent.com/93105083/170514539-02a47fcb-e6a5-4a2b-9f1a-0145b962071a.png)

<br><br>

## Exception과 Error의 차이는?

![image](https://user-images.githubusercontent.com/93105083/170514586-926aca55-93d0-442f-8dd9-956619b6d999.png)

**에러**

- **컴파일 에러:** 컴파일 에러는 말 그대로 컴파일 과정에서 일어나는 에러
    - 자바 컴파일러가 문법 검사를 통해 오류를 잡음
- **런타임 에러:** 실행 과정에서 일어나는 에러
    - 컴파일이 문제없이 되더라도 실행 과정(runtime)에서 오류 발생 가능 → 런타임 에러를 방지하기 위해서는 프로그램 실행 도중 일어날 수 있는 모든 경우의 수를 고려
    1. **예외(Exception)**
        - 메모리 부족(OutOfMemoryError), 스택오버플로우(StackOverFlowError)처럼 JVM이나 하드웨어 등의 기반 시스템의 문제로 발생
        - 발생했을 때를 대비해서 프로그래머가 뭔가 할 수 있는게 없음
        - 발생하는 순간 무조건 프로그램은 비정상 종료
    2. **에러(Error)**
        - 발생하더라도 프로그래머가 미리 적절한 코드를 작성해서 프로그램이 비정상적으로 종료되지 않도록 핸들링 가능

**Throwable 클래스**

- Exception과 Error 클래스는 Throwable 클래스를 상속받아 처리
    - Exception이나 Error를 처리할 때 Throwable로 처리해도 무관
- getMessage()
    - 예외 메시지를 String형태로 제공받음
    - 예외가 출력되었을 때 어떤 예외가 발생되었는지를 확인할 때 매우 유용
    - 메시지를 활용하여 별도의 예외 메시지를 사용자에게 보여주려고 할 때 활용
- toString()
    - 예외메시지를 String형태로 제공음
    - getMessage() 메소드보다는 약간 더 자세하게, 예외 클래스 이름도 같이 제공
- printStackTrace()
    - 가장 첫 줄에는 예외 메시지를 출력하고, 두 번째 줄부터는 예외가 발생하게 된 메소드들의 호출 관계(스택 트레이스를)출력
    - printStackTrace()는 서비스 운용시 사용 **금지**

<br><br>

## 자바가 제공하는 예외 계층 구조

자바 → 실행 시 발생할 수 있는 오류(Exception & Error)를 클래스로 정의

![image](https://user-images.githubusercontent.com/93105083/170514694-979e3ea2-00ef-422e-a0a0-2df50fa8ddcf.png)

![image](https://user-images.githubusercontent.com/93105083/170514742-f2b208da-293a-414b-b9c6-7382dccd5130.png)

![image](https://user-images.githubusercontent.com/93105083/170514788-fc5f4914-617b-4012-926b-a499f2ee823a.png)

- Exception과 Error는 Throwable 클래스 상속
- Throwable은 Object를 직접 상속
- 일반예외 (Exception) *:* 예외 Exception을 상속받지만, RuntimeException은 상속받지 않음
- 실행예외 (Runtime Exception) *:* 실행 예외는 RuntimeException을 상속 받음

<br><br>

## RuntimeException과 RE가 아닌 것의 차이는?

Exception 상속받는 클래스

- **UncheckedException**
    - **RuntimeException**, 그 하위 클래스 + Error와 그 하위 클래스
        - RuntimeException 종류
            1. NullPointerException(NPE)
            2. ArrayIndexOufOfBoundsException
    - 컴파일러가 예외를 처리하거나 선언하도록 강제X,  프로그래머가 처리
    - 명세 안 해도 되는 이유
        - 프로그램 코드의 문제로 발생하는 예외
        - RuntimeException은 프로그램 어디서나 매우 빈번하게 발생 가능 → 모든 RuntimeException을 메서드에 명시하도록 강제하는 것은 프로그램의 명확성을 떨어뜨림
- **CheckedException**
    - RuntimeException 제외한 모든 Exception
    - 컴파일 시점에서 확인될 수 있는 예외
        - Checked Exception 발생 → try-catch로 예외를 처리하거나 thorws로 예외를 던져줘야 함
    - 해당 메서드가 발생시킬 수 있는 예외를 명세하도록 강제
        - 명세 해야하는 이유: 메서드를 호출하는 쪽은 그 메서드가 어떤 예외를 발생시킬 수 있는가에 대해 반드시 알아야 하기 때문

- 클라이언트가 exception을 적절히 회복할 수 있을 것이라고 예상되는 경우 CheckedException
- 그렇지 않은 경우 UncheckedException

<br><br>

## 커스텀한 예외 만드는 방법

- Throwable을 직접 상속 받는 클래스: Exception과 Error
- Error와 관련된 클래스는 개발자가 손대서는 절대 안 됨
- 직접 만들땐 Exception을 처리하는 클래스라면 `java.lang.Exception` 클래스의 상속을 받는 것이 좋다.

```java
public class ExceptionSample {

    public static void main(String[] args) throws NotEnoughStockException {
        stockEnoughMethod(5);
    }

    static void stockEnoughMethod(int stock) throws NotEnoughStockException {
        if (stock < 1) {
            throw new NotEnoughStockException("재고 부족");
        }
    }
}

class NotEnoughStockException extends Exception {
    public NotEnoughStockException(String message) {
        super(message);
    }
}
```

- super() 메소드
    - `super()` 메소드는 부모 클래스의 생성자를 호출할 때 사용
    - 자식 클래스의 인스턴스를 생성 → 해당 인스턴스에는 자식 클래스의 고유 멤버뿐만 아니라 부모 클래스의 모든 멤버까지 포함

<br>

**예외 되던지기(exception re-throwing)**

```java
public class ExceptionSample {

    public static void main(String[] args) {
        try {
            stockEnoughMethod();
        } catch (Exception e) {
            System.out.println("main에서 예외 처리");
        }
    }

    static void stockEnoughMethod() throws Exception {
        try {
            throw new Exception();
        } catch (Exception e) {
            System.out.println("stockEnoughMethod에서 예외 처리");
            throw e;
        } 
    }
}
```

- 한 메서드에서 발생할 수 있는 예외가 여러 개인 경우 → 일부는 메서드 내부에서 처리, 일부는 선언부에 지정해서 메서드를 호출한 쪽에서 처리
- 하나의 예외에 대해서도 양쪽에서 처리 가능 → 예외 되던지기
    - catch문에서 throw를 사용해 예외를 다시 던짐

<br>

**Chained Exception**

한 예외가 다른 예외를 발생시킴

ex. 예외 A가 예외 B를 발생시킴

- A: “원인 예외(cause exception)” : 원인 예외는 initCause()로 지정 가능
- initCause()는 Throwable 클래스에 정의되어 있기 때문에 모든 예외 클래스에서 사용 가능

```java

public class ExceptionSample {

    public static void main(String[] args) {
        try {
            stockEnoughMethod(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void stockEnoughMethod(int stock) throws IOException{
        try {
            if (stock == 0) {
                throw new IllegalArgumentException();
            }
        } catch (IllegalArgumentException e) {
            IOException ioException = new IOException();
            ioException.initCause(e);  // IOException의 예외를 IllegalArgumentException으로 지정
            throw ioException;
        }
    }
}
```

```java
public class ExceptionSample {

    public static void main(String[] args) {
        try {
            stockEnoughMethod(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static void stockEnoughMethod(int stock){
        try {
            if (stock == 0) {
                throw new IllegalArgumentException();
            }
        } catch (IllegalArgumentException e) {
            throw new RuntimeException(e);
        }
    }
}
```

<br>

**자바 예외 처리 전략**

- 실행 시 발생할 확률이 매우 높은 경우 → `extends Exception` 대신 `extends RuntimeException`
    - `try-catch`로 묶지 않아도 컴파일시에 예외가 발생 X

<br><br>
<hr>

**출처**

[https://wisdom-and-record.tistory.com/46](https://wisdom-and-record.tistory.com/46)

[https://sujl95.tistory.com/62](https://sujl95.tistory.com/62)

[https://catch-me-java.tistory.com/46](https://catch-me-java.tistory.com/46)

[https://velog.io/@youngerjesus/자바-예외-처리](https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)
